### PR TITLE
Added missing keywords

### PR DESCRIPTION
**Pull request by ascillato**

### CODE REVIEW

**Comment by envy** [comment]
Hi,

please make sure that you use tabs instead of spaces inside the keywords.txt: https://www.arduino.cc/en/Hacking/LibraryTutorial

It looks like some of the lines use spaces.

**Comment by ascillato** [comment]
done :+1:

**Comment by envy** [comment]
Now everything is spaces, not tabs.

**Comment by ascillato** [comment]
Sorry, I pressed TAB in all those but using the web editor of github. So seems that it is converting everything to spaces?

Anyway, now I did this change using atom+github desktop

Please, re check it. Thanks.

**Review by spacegaier — APPROVED** [review]
Seems to be all tabs now

**Comment by spacegaier** [comment]
@ascillato Why did you delete the PR? It hasn't been merged in yet.

**Comment by ascillato** [comment]
The PR was incomplete and old. A new one should be done.

**Pull request closed without merging**
